name: Generate Android Keystore

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore taja-release.keystore -alias taja -keyalg RSA -keysize 2048 -validity 10000 -storepass "tajacart2026" -keypass "tajacart2026" -dname "CN=Taja Cart, OU=Taja, O=Taja, L=City, ST=State, C=IN"
          
      - name: Extract SHA-1 Fingerprint
        run: |
          echo "=================================================="
          echo "HERE IS YOUR SHA-1 FINGERPRINT FOR GOOGLE CLOUD:"
          keytool -list -v -keystore taja-release.keystore -alias taja -storepass "tajacart2026" | grep SHA1
          echo "=================================================="
          
      - name: Upload Keystore for User to Download
        uses: actions/upload-artifact@v4
        with:
          name: taja-release-keystore
          path: taja-release.keystore
